### ISSUE TITLE
[feature request] Add/fix default CPU governor support for Ryzen 5000

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/linux-tkg#132] opened 2020-11-27 01:09 UTC
I've always had the default CPU governor be set in `customization.cfg` to performance, but I was previously running a 3800X and a 3600X and 2600X before that. I just got a 5800X yesterday, and while I can ***change*** the CPU governor to performance manually using cpupower, the default governor is schedutil, even though I'm using the same kernel that sets performance as the governor perfectly fine on my 3800X. 

I'm happy to help in any way you might need to get this done

**Comment by Tk-Glitch** [comment] 2020-12-02 12:03
If I knew what the problem is, sure. Outside of the intel_pstate mess lately I'm not aware of a change that could lead to such a result. On top of that, the intel_pstate changes will affect all x86_64 CPUs, so there's no reason for it to be different on zen3 specifically. I'll dig.

**Comment by gardotd426** [comment] 2020-12-02 12:44
Yeah, I wish it had at least given an error or something, so I could give you more information. Like I said, I'm happy to help however I can, just let me know if I need to test any builds or get you more info, or hell, take it upstream.

**Comment by Tk-Glitch** [comment] 2021-03-09 16:02
Was the feb 3 change a fix for this?

**Comment by gardotd426** [comment] 2021-03-09 16:42
I had just worked around it by doing the whole kernel commandline thing, setting the governor that way, but I'll go ahead and test it out now and get back to you asap, and if so, we can go ahead and close.

**Closed** 2021-06-17 11:06 UTC
Labels: upstream
