### ISSUE TITLE
[Nvidia-tkg-dkms Compatibility] `5.17.2-255-pds-llvm` Fails to Build Against `Nvidia-all`

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/linux-tkg#498] opened 2022-04-11 23:59 UTC
This occurs regardless of whether `lto-thin` was used or no lto was used:
```
==> dkms install --no-depmod nvidia/510.60.02 -k 5.17.2-255-tkg-pds-llvm
Error! Bad return status for module build on kernel: 5.17.2-255-tkg-pds-llvm (x86_64)
Consult /var/lib/dkms/nvidia/510.60.02/build/make.log for more information.
==> WARNING: `dkms install --no-depmod nvidia/510.60.02 -k 5.17.2-255-tkg-pds-llvm' exited 10
```
[make.log](https://github.com/Frogging-Family/linux-tkg/files/8468456/make.log)
[linux-tkg.cfg.zip](https://github.com/Frogging-Family/linux-tkg/files/8468457/linux-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment] 2022-04-12 00:17
This is because you don't have the resolve_btfids from your previous issue. Your current kernel configuration is incorrect for Nvidia.

**Comment by ThisNekoGuy** [comment] 2022-04-12 00:19
Uhhhh, I'm a bit confused... :thinking:
How do I explicitly know when I do or don't have it?

**Comment by Tk-Glitch** [comment] 2022-04-12 00:21
The better question would be what did you change in your defconfig vs default to get this result? :frog:

**Comment by ThisNekoGuy** [comment] 2022-04-12 00:23
I'm trying to figure that out, I can't seem to tell what in there would cause that, I've compared them three times :woozy_face:

**Comment by Tk-Glitch** [comment] 2022-04-12 00:24
Make sure you have those in:
```
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_BTF=y
CONFIG_DEBUG_INFO_BTF_MODULES=y
```

**Comment by ThisNekoGuy** [comment] 2022-04-12 00:33
I'll try that; though, that last one `CONFIG_DEBUG_INFO_BTF_MODULES` isn't appearing in the Kconfig menu

**Comment by Tk-Glitch** [comment] 2022-04-12 00:37
`depends on: CONFIG_DEBUG_INFO_BTF && CONFIG_MODULES && CONFIG_PAHOLE_HAS_SPLIT_BTF`

**Comment by ThisNekoGuy** [comment] 2022-04-12 00:42
`CONFIG_PAHOLE_HAS_SPLIT_BTF` isn't in here for some reason, which might explain that a little bit

**Comment by ThisNekoGuy** [comment] 2022-04-12 01:18
Is it just me or is there something else I'm just not noticing about why I'm suddenly getting `lld` zlib errors?
As a result, two more errors follow it and the build fails :/

[kernelconfig.new.zip](https://github.com/Frogging-Family/linux-tkg/files/8468757/kernelconfig.new.zip)
[linux-tkg.cfg.zip](https://github.com/Frogging-Family/linux-tkg/files/8468758/linux-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment] 2022-04-12 01:49
I simply cannot reproduce any of this. I'm also using an untouched defconfig and GCC so there's that, but Nvidia modules are building just fine. You seem to have other issues here.

**Comment by ThisNekoGuy** [comment] 2022-04-12 01:54
Hmm... Okay, I'll just start from scratch then, I guess
Hopefully it just doesn't happen again :/

**Comment by ThisNekoGuy** [comment] 2022-04-12 03:53
Oh my god, undoing that this time fixed it :skull_and_crossbones: 
Well, at least it built now... not with llvm though; although, I'm not sure I want to mess with that again right now Lol

**Comment by OneOfOne** [comment] 2022-04-12 19:02
I haven't changed anything since 5.17.1 and I have ran into this as well, I'm not using a custom kernel config.

```
./tools/bpf/resolve_btfids/resolve_btfids: No such file or directory
```
this is for all DKMS modules, not just nvidia.

**Comment by skeevy420** [comment] 2022-04-12 19:27
Yeah, none of my modules have been building today either. After numerous builds I noticed something and I think it's line 934 of the PKGBUILD. It's doing a file check on a directory.

It should be using a -d instead of a -e. There are also some parentheses that could be added and/or moved around. I just started a build with the following changes and I'll have the results in a little bit.

`  if [ "$_basever" -ge "516" ] && [ -d "$builddir/tools/bpf/resolve_btfids" ]; then
    install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids
  fi`

**Comment by skeevy420** [comment] 2022-04-12 20:18
I just checked the Arch sources and[ they updated their defconfig](https://github.com/archlinux/svntogit-packages/commit/161a75ed5bf2639b85cf6bba2acad6ac8e9b2cb5) to include

```
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
```
so I'm trying that now. Finger's crossed.

**Comment by ThisNekoGuy** [comment] 2022-04-12 20:34
I have this set for GCC, and it builds against Nvidia, but I haven't been able to get it to load the driver for the 6 hours - trying various things

**Comment by Tk-Glitch** [comment] 2022-04-12 20:35
I have changed it a bit so it doesn't break for people with a working env. Please pull and try with those changes.

**Comment by ThisNekoGuy** [comment] 2022-04-12 20:49
Yeah, that seems to be the issue with the GCC builds I've been doing too; I just have no clue what's making `resolve_btfids` absent from where it should be

**Comment by ThisNekoGuy** [comment] 2022-04-12 21:06
> Make sure you have those in:
> 
> ```
> CONFIG_DEBUG_INFO=y
> CONFIG_DEBUG_INFO_BTF=y
> CONFIG_DEBUG_INFO_BTF_MODULES=y
> ```
> 
> They are enabled by default in Arch's defconfig btw.

Unironically, this is what fixes it

**Comment by skeevy420** [comment] 2022-04-12 21:43
> I have changed it a bit so it doesn't break for people with a working env. Please pull and try with those changes.

That was enough to fix building 5.16 dkms modules for me. 

In addition to CONFIG_BPF_UNPRIV_DEFAULT_OFF=y I mentioned above, upstream Arch has also [enabled DAMON](https://github.com/archlinux/svntogit-packages/commit/9dedaae16b42d91af453d2a85b241a2baa1ed701) as well as [disabled ZERO_CALL_USED_REGS](https://github.com/archlinux/svntogit-packages/commit/ffa521f3c6494bb6d272c1fce0aada4a2ab825f9) to their 5.16 defconfig.

**Comment by Tk-Glitch** [comment] 2022-04-12 22:36
I have synchronized our 5.16 defconfig with Arch's latest

**Comment by ThisNekoGuy** [comment] 2022-04-13 06:42
So, I narrowed down the issue I was having with the Nvidia driver (besides the original linking issue you helped with @Tk-Glitch )
It's either one or both of these, as far as I can tell:
```
CONFIG_AMD_MEM_ENCRYPT
CONFIG_SYSFB_SIMPLEFB
```
Neither are enabled in the default config, but it seems either one or both (haven't checked that) either cause me to infinitely stall on boot or boot to a green screen (which might be by-products of them both) with the proprietary Nvidia driver

**Comment by skeevy420** [comment] 2022-04-13 14:00
I think it's [SIMPLEFB](https://bugs.archlinux.org/task/74203). That bug report describes everything you're describing.

**Comment by ThisNekoGuy** [comment] 2022-04-13 20:26
I've identified them:
```
CONFIG_AMD_MEM_ENCRYPT=y
CONFIG_SYSFB_SIMPLEFB=y
CONFIG_FB_SIMPLE=y
```

`AMD_MEM_ENCRYPT` prevents proper booting for some reason
`SYSFB_SIMPLEFB` does cause that green-screen issue
`FB_SIMPLE` causes video to be cut out entirely; only using `FB_EFI` over it doesn't break it

**Comment by Tk-Glitch** [comment] 2022-04-14 02:31
Outside of `AMD_MEM_ENCRYPT` (which only enables support for the feature, and not actually turning it on as long as it's not enabled through userspace or with `AMD_MEM_ENCRYPT_ACTIVE_BY_DEFAULT`), you have made changes to our defconfig. As expected, playing with the kernel config can break stuff if done incorrectly, and we can't really offer support for that :frog:
Closing.

**Closed by Tk-Glitch** 2022-04-14 02:31 UTC
Labels: config issue

**Comment by ThisNekoGuy** [comment] 2022-04-14 03:43
@Tk-Glitch I'm aware Lol
Aside from fixing my own mess though, I'm communicating that so that maybe this information can be put into a note for proprietary Nvidia users somewhere so they don't make the same mistakes I did Lol

Would save others literally dozens of hours diagnosing this

**Comment by Tk-Glitch** [comment] 2022-04-14 04:11
Of course. It was in no way critical, just very objective. Sorry :frog:

It's kind of a sensitive matter if we get deep into it, but ultimately we are offering a package that is already very configurable without touching the config yourself at any time, and testing and offering support for the combinations you can make that way is already pretty time consuming and complex.

Having that into a note of some sort would be opening a world of issues imho, as you can break your kernel and its features with hundreds of config combinations - even more so Nvidia machines - which would be a huge confusing PITA to document and maintain imho. That's also why we are offering some default config tweaks on top of the Arch base, so most users won't have to actually modify the config themselves while still getting some of the benefits of doing so like reduced debugging or skipping the modules you don't need with modprobed-db.

A warning regarding the dangers of modifying the configuration would be more valuable as is, but I believe neither solution is actually a solution. I'm open to discussion if you think it needs more care, but I'm not convinced currently.

**Comment by ThisNekoGuy** [comment] 2022-04-14 04:52
I understand, it's alright

What you're saying makes sense though; although, I think the likelihood that the Nvidia drivers needing anything else to avoid or need as a prerequisite in the future to detract from that theoretical not is a bit slim... Similar to what you mentioned though, the default config concerning those modules works perfectly fine for Nvidia, I was just thinking something that says:
```
"Definitely don't touch these if you want a display for proprietary Nvidia; don't even touch the rest of the config *manually* unless you know what you're doing
```
But I can understand that could open the door for problem hunting...

Idk, it's difficult because it's not necessarily something to make people discouraged from learning/doing, but it's also an easy pitfall to get lost in, which is why I started from scratch with the tkg default config and only really stripped modules like: industria hardwarel, super niche hardware, radio, opposite CPU support (I use an AMD CPU so I stripped out Intel CPU support), Xen, VirtualBox, VMware, etc; I left a lot of everything from the default config alone (for example, I didn't even touch networking at all because there are a lot of those modules and they're pretty technical to understand), so once I got rid of everything that I could make sense of that was obvious didn't apply to both my system and most consumer desktops in general, it would be easier to just leave overly complex things alone and slowly figure out how to get Nvidia support to behave

(Sorry, felt like I ranted there, I'm kind of thinking out loud but also trying to prod at your brain to see what you think)

**Comment by AdelKS** [comment] 2022-04-14 08:32
If you want to really go down the rabbit hole, Gentoo has extensive documentation on how to build the kernel config from the ground up, here's what you needed with Nvidia : https://wiki.gentoo.org/wiki/NVIDIA/nvidia-drivers#Kernel
If you want to meddle with other things in the kernel config, look up Gentoo documentation about it

**Comment by ThisNekoGuy** [comment] 2022-04-14 13:10
> If you want to really go down the rabbit hole, Gentoo has extensive documentation on how to build the kernel config from the ground up, here's what you needed with Nvidia : https://wiki.gentoo.org/wiki/NVIDIA/nvidia-drivers#Kernel If you want to meddle with other things in the kernel config, look up Gentoo documentation about it

I already looked at that; it's because I followed that advice that I ended up with this problem

**Comment by AdelKS** [comment] 2022-04-14 16:00
I see, then that documentation needs to be updated probably.

**Comment by ThisNekoGuy** [comment] 2022-04-14 17:51
In my experience, the Gentoo wiki doesn't get updated as often as it honestly should; it's 1 of the 3 only reasons why I don't use Gentoo :/

**Comment by AdelKS** [comment] 2022-04-14 18:24
If you pinpoint properly the reasons behind each config option you should absolutely update the page yourself. That's how the arch wiki is up to date anyway, users realizing things need to get updated

**Comment by ThisNekoGuy** [comment] 2022-04-14 18:37
I'm aware, but it was bad enough for Gentoo that the installation guide to set up the system for a DE easily caused circular dependency problems and didn't even clearly provide an up-to-date method on how to fix it; my issue with Gentoo in general is with the wiki seemingly never being up-to-date on how to prevent or solve problems, which is shocking to me considering how dense of a collection of information it is

The other thing... I generally don't have good experiences with trying to get distro wiki's updated; it tends to turn into changes being taken down arbitrarily
