### ISSUE TITLE
Failing to compile on Fedora 34, kernel-headers outdated (but up to date according to dnf)

### ISSUE THREAD

**Issue by toukoAMG** [Frogging-Family/linux-tkg#271] opened 2021-06-17 20:00 UTC
I tried to compile 5.11 upds and 5.12 cacule, but they both failed as they said
[https://i.imgur.com/1YrKKGv.png](url)
running kernel-headers 5.12.9-300

**Comment by xsmaze** [comment] 2021-06-18 01:15
I've also had this problem on a clean install of Fedora 34 on 5.12.10-300.

**Comment by AdelKS** [comment] 2021-06-18 09:06
Hello, I cannot see the error message, can you just copy your entire build log and attach it ? Please also provide your `customization.cfg`. I will have a look.

**Comment by rangerAMG** [comment] 2021-06-18 15:21
[here is customization.cfg](https://pastebin.com/2u1nKbDp)
and as for the build log, if you mean the output from the terminal when I install it, [here it is](https://pastebin.com/gWn3xm2F)

**Comment by AdelKS** [comment] 2021-06-18 17:11
Oh I see, it's a duplicate of #173 that got closed even though it didn't get fixed. Unfortunately, I do not know what's the root of this issue up until now... :/

**Comment by rangerAMG** [comment] 2021-06-18 17:13
oh i see... well is there any other way to install the kernel?

**Comment by AdelKS** [comment] 2021-06-18 17:17
Actually, there is, you can use `Generic` as distro, you will need to have `dracut` installed. And the installed files **will not be tracked by** `dnf`. 
- A folder gets installed in `/lib/modules` 
- The kernel image, the initramfs and a file called `System.map` get installed in `/boot`. 
- System headers get installed in `/usr/src` and they overwrite few files that get installed by one of the Fedora packages, you would need to reinstall that package to restore the original headers
- To uninstall that, you need to remove all that manually.

**Comment by rangerAMG** [comment] 2021-06-18 17:19
alright, will try this

thank you

**Comment by AdelKS** [comment] 2021-06-18 17:20
Quick googling gives this: `sudo dnf install kernel-devel`, try that ? (basically reinstall the `kernel-devel` package).

**Comment by rangerAMG** [comment] 2021-06-18 18:39
I tried that, it doesn't seem to work

**Comment by AdelKS** [comment] 2021-06-18 20:19
Oh wait, you need to do `./install.sh install` not `config`

**Comment by rangerAMG** [comment] 2021-06-19 12:04
I tried that, but it just exited
On a sidenote, I think I found out why the kernel wouldn't install, the kernel headers are located in a different place than normal, as when I was trying to install some dkms driver, it said it couldn't find the kernel headers at the place
`Error! echo
Your kernel headers for kernel 5.12.10-300.fc34.x86_64 cannot be found at
/lib/modules/5.12.10-300.fc34.x86_64/build or /lib/modules/5.12.10-300.fc34.x86_64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.`

**Comment by AdelKS** [comment] 2021-06-19 12:08
> I tried that, but it just exited

Can you attach the output on your terminal ? (you can make a text file then drag and drop it in the text you write here, you don't need to use a third-party service)

>  the kernel headers are located in a different place than normal, as when I was trying to install some dkms driver, it said it couldn't find the kernel headers at the place

Interesting find, I will see if I can do something based on this new information

**Comment by iWeaker4you** [comment] 2021-06-22 05:34
> I tried that, but it just exited
> On a sidenote, I think I found out why the kernel wouldn't install, the kernel headers are located in a different place than normal, as when I was trying to install some dkms driver, it said it couldn't find the kernel headers at the place
> `Error! echo Your kernel headers for kernel 5.12.10-300.fc34.x86_64 cannot be found at /lib/modules/5.12.10-300.fc34.x86_64/build or /lib/modules/5.12.10-300.fc34.x86_64/source. You can use the --kernelsourcedir option to tell DKMS where it's located.`

It is because the symlink is not generated correctly, here I have an example that the symlink is badly done, in fact the build "folder" marks it in red
![Captura de pantalla de 2021-06-21 22-25-23](https://user-images.githubusercontent.com/49424816/122868412-c46dc400-d2df-11eb-9802-7c4747cc4231.png)

But with the tkg kernel, the symlink is correct. I leave image.

![Captura de pantalla de 2021-06-21 22-27-23](https://user-images.githubusercontent.com/49424816/122868542-ed8e5480-d2df-11eb-9812-1a2f564c738f.png)

If the folder appears in red, delete it and apply this.

`sudo ln -s  /usr/src/kernels/5.12.11-301.fsync.fc34.x86_64+debug /lib/modules/5.12.11-301.fsync.fc34.x86_64/build`



Of course, it must be your kernel version in both cases, I have that kernel version that did not work but already applying this, it works without problems.

**Comment by AdelKS** [comment] 2022-10-02 13:30
Hello! Please try PR https://github.com/Frogging-Family/linux-tkg/pull/610 to confirm that it fixes this issue. It worked like a charm in my VM.

Adel

**Comment by Tk-Glitch** [comment] 2022-10-02 16:34
Should be fixed with https://github.com/Frogging-Family/linux-tkg/commit/1d063ca32634997616d9cb1da81253bdedc67054

**Closed by Tk-Glitch** 2022-10-02 16:34 UTC
