### ISSUE TITLE
Some problems compiling Linux 6.3.4-tkg-pds kernel for fedora 38

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#738] opened 2023-05-07 04:08 UTC
I've always used the tkg pds kernel, but now I'm having a series of problems and messages that are preventing me from compiling for fedora 38. I made a post reporting the problem https://github.com/Frogging-Family/linux-tkg/issues/735 issues but I still couldn't get a solution.

I would be very grateful for the help.

OS: Fedora 38 64bit
kernel current: 6.2.16-tkg_pds
kernel: 6.3.4-tkg_pds (errors when compiling)

**Comment by whitehara** [comment] 2023-05-07 18:53
Unfortunately, I don't know what is the cause of your problem. But I also use these patches and provide the modified patches and kernel rpms for fedora.

Please refer them if you like.

Modified patches:
https://github.com/whitehara/kernel-patch-fedora

Kernel rpms:
https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg/

**Comment by Everest10** [comment] 2023-05-07 20:01
> Unfortunately, I don't know what is the cause of your problem. But I also use these patches and provide the modified patches and kernel rpms for fedora.
> 
> Please refer them if you like.
> 
> Modified patches: https://github.com/whitehara/kernel-patch-fedora
> 
> Kernel rpms: https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg/

Ok but has precompiled version PDS for ivybridge ?

**Comment by whitehara** [comment] 2023-05-08 11:28
I just finished to make. But I don't have a test environment. Please try it at your own risk.

https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg-ivybridge-pds/

**Comment by Everest10** [comment] 2023-05-08 21:39
> I just finished to make. But I don't have a test environment. Please try it at your own risk.
> 
> https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg-ivybridge-pds/

There is no kernel-6.3.1-200_tkg_ivybridge_pds.fc38 just 6.3.1-200_tkg_alderlake_preempt.fc38 intel 12Gen

**Comment by whitehara** [comment] 2023-05-09 05:51
> > I just finished to make. But I don't have a test environment. Please try it at your own risk.
> > https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg-ivybridge-pds/
> 
> There is no kernel-6.3.1-200_tkg_ivybridge_pds.fc38 just 6.3.1-200_tkg_alderlake_preempt.fc38 intel 12Gen

Sorry, I made a mistake in the instruction on that project page. (Fixed)
You need to enable "whitehara/kernel-tkg-ivybridge-pds" project with the below command.
`
dnf copr enable whitehara/kernel-tkg-ivybridge-pds
`

**Comment by Everest10** [comment] 2023-05-09 09:26
> > > I just finished to make. But I don't have a test environment. Please try it at your own risk.
> > > https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg-ivybridge-pds/
> > 
> > 
> > There is no kernel-6.3.1-200_tkg_ivybridge_pds.fc38 just 6.3.1-200_tkg_alderlake_preempt.fc38 intel 12Gen
> 
> Sorry, I made a mistake in the instruction on that project page. (Fixed) You need to enable "whitehara/kernel-tkg-ivybridge-pds" project with the below command. `dnf copr enable whitehara/kernel-tkg-ivybridge-pds`

Tested here and freezes the boot

**Comment by whitehara** [comment] 2023-05-09 20:49
Thanks for your test. I found CPU CONFIG is not correct. So I recompiled.
If you have a time, please try it again.

**Comment by Everest10** [comment] 2023-05-10 04:48
> Thanks for your test. I found CPU CONFIG is not correct. So I recompiled. If you have a time, please try it again.

I enabled your repo again and did dnf update to get the update again and freezes the boot again.

[log messages.txt](https://github.com/Frogging-Family/linux-tkg/files/11438176/log.messages.txt)

**Comment by whitehara** [comment] 2023-05-10 05:32
I didn't update the version number. Please remove the previous kernel which failed to boot, then download and reinstall again.

If the problem continues, I think the cause is not related to CPU CONFIG.
In that case, and if you still want to try it, please make a new issue on my github repo below. We can continue there.

https://github.com/whitehara/kernel-patch-fedora/issues

**Comment by whitehara** [comment] 2023-05-11 05:31
> > I didn't update the version number. Please remove the previous kernel which failed to boot, then download and reinstall again.
> > If the problem continues, I think the cause is not related to CPU CONFIG. In that case, and if you still want to try it, please make a new issue on my github repo below. We can continue there.
> > https://github.com/whitehara/kernel-patch-fedora/issues
> 
> I removed the previous kernel and installed again, but freezes the boot.

I think it takes a time to solve. At first, we need to know what is a cause of the freeze.
And maybe you can try another custom kernel.

Do you still want to try this kernel?
If so, please make a new issue on my repo. Let's continue there.
https://github.com/whitehara/kernel-patch-fedora/issues

**Comment by AdelKS** [comment] 2023-05-29 13:03
Let's close this issue and discuss on the latest one #751

**Closed by AdelKS** 2023-05-29 13:03 UTC
