### ISSUE TITLE
Unusually (?) high space requirement for building 5.8

### ISSUE THREAD

**Issue by Kiwii** [Frogging-Family/linux-tkg#51] opened 2020-08-20 05:01 UTC
Not sure if this is even a bug or not, but building 5.8 needs more than twice the amount of free disk space to build successfully compared to previous kernels.

I'm used to compiling the kernel in tmpfs with a size of 7.8 GiB. To my surprise, it ran out of space. So I moved the repo to my primary drive and tried again... and ran out of space. Had to uninstall some games to get it to compile and noticed it used as much as 14.7 GiB at some point.

Is this normal/expected for 5.8?

**Comment by Tk-Glitch** [comment] 2020-08-27 11:47
After a quick check on 5.8.5 it seemed fine. Could you please retest and see if you can reproduce the issue?

**Comment by Kiwii** [comment] 2020-08-28 10:18
Unfortunately yes. This happens maybe 10 to 15 minutes into the build: https://i.imgur.com/xlVTqCZ.png (followed by the build failing from tmpfs being full) 

I can reproduce it with a fresh clone of the repo with no changes to the config. I also tried _noccache="true" and _force_all_threads="false" (with -j6 in makepkg.conf on a six core Ryzen 5) but neither seem to affect it.

**Comment by JDC2389** [comment] 2020-08-28 10:54
I get this too, it seems to be something like 16+- gigs to build in tmpfs and I have 24gb so I remount to 18gb temporarily. Upgrade to 24-32gb is my all rounder recommendation but yes building got a lot heavier overnight and I've seen reports from other frogs to this effect regarding space requirements. 👍

**Comment by gardotd426** [comment] 2020-09-13 13:30
This is true, it happens with 5.9 too I think. 

I literally had to change my ~/tmp tmpfs partition where my `makepkg` builds to 22G. I don't know what's going on, but I noticed it a few weeks ago.

**Comment by Tk-Glitch** [comment] 2020-10-26 16:29
It seems to be expected and universal since 5.8. Marking as upstream.

**Comment by redgloboli** [comment] 2021-03-12 16:55
i had this too, but it seems to be gone now. i didn't have to resize /tmp since a few builds anymore.

**Comment by Tk-Glitch** [comment] 2021-03-12 16:57
I admit I haven't checked, but some RC (I think it might have been 5.10) fixed it at some point. Let's close.

**Closed by Tk-Glitch** 2021-03-12 16:57 UTC
Labels: upstream
