### ISSUE TITLE
Windows VM crashing/freezing for a few minutes on linux-tkg.

### ISSUE THREAD

**Issue by F1uk369** [Frogging-Family/linux-tkg#569] opened 2022-08-12 10:16 UTC
- I have encountered this bug on Arch Linux.
- This bug only is present if I use linux-tkg 5.19, if I use stable, 5.18.16-arch1-1, my Windows single GPU passthrough machine does not freeze/crash. It eventually comes back, and says nvlddmkm has recovered from something, in event viewer.
Please let me know of any logs required!

**Comment by Tk-Glitch** [comment] 2022-08-12 16:53
Do you have your config file or selected options at hand?
In this specific case, the most likely culprits would be a regression with 5.19 or usage of an alternative CPU scheduler (possibly coupled with a tool like gamemode or ananicy, but that might be a stretch).

If you're not using CFS, your motherboard/CPU/RAM combo might be slightly unstable and that instability exacerbated by the more aggressive and latency sensitive scheduling (if you have an OC in place, try with lower clocks).

Using CFS *should* restore the usual behavior if it's not a 5.19 specific issue.

**Comment by Tk-Glitch** [comment] 2022-09-30 12:07
Couldn't reproduce the issue on my end. Closing due to no feedback.

**Closed by Tk-Glitch** 2022-09-30 12:07 UTC
