### ISSUE TITLE
Kernel Headers Fails to Package: cannot stat `...` no such file or directory

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/linux-tkg#497] opened 2022-04-11 22:13 UTC
```
  -> Workaround missing winesync header
  -> Set the winesync module to be loaded at boot through /etc/modules-load.d
  -> Installing udev rule for winesync
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
usr/share/doc/linux517-tkg-pds-llvm/customization.cfg
==> Creating package "linux517-tkg-pds-llvm"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Starting package_linux517-tkg-pds-llvm-headers()...
  -> Installing build files...
install: cannot stat 'tools/bpf/resolve_btfids/resolve_btfids': No such file or directory
==> ERROR: A failure occurred in package_linux517-tkg-pds-llvm-headers().
    Aborting...
  -> exit cleanup done
```
[.config zip archive](https://github.com/Frogging-Family/linux-tkg/files/8468084/config.zip)
[linux-tkg.cfg.zip](https://github.com/Frogging-Family/linux-tkg/files/8468087/linux-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment] 2022-04-11 22:31
Duplicate of https://github.com/Frogging-Family/linux-tkg/issues/409

**Closed** 2022-04-11 23:00 UTC

**Comment by ThisNekoGuy** [comment] 2022-04-11 23:22
@Tk-Glitch I just `git reset` the local repo over here and it still happens >_>
