### ISSUE TITLE
Void Linux error: version must contain at least one digit.

### ISSUE THREAD

**Issue by PlanetNoobGotHacked** [Frogging-Family/linux-tkg#320] opened 2021-09-26 06:59 UTC
I'm installing linux-tkg on Void Linux and I'm getting these errors:

`[planet@planetspc void-packages]$ ./xbps-src pkg -j$(nproc) linux-tkg`
`/home/planet/void-packages/srcpkgs/linux-tkg/template: line 59: /home/planet/void-packages/masterdir/builddir/linux-tkg/cpuschedset: No such file or directory`
`/home/planet/void-packages/srcpkgs/linux-tkg/template: line 61: /home/planet/void-packages/masterdir/builddir/linux-tkg/versel: No such file or directory`
`=> ERROR: version must contain at least one digit.`

**Comment by AdelKS** [comment] 2021-09-27 14:49
@Ann1kaB can you have a look at this ?

**Comment by PlanetNoobGotHacked** [comment] 2021-10-29 18:06
@AdelKS my solution was to just add linux-tkg patches to kernel build

**Comment by AdelKS** [comment] 2021-10-30 18:55
Yea that's one way to do it, but you also need to reproduce the config file changes.

**Comment by Ann1kaB** [comment] 2021-10-30 19:36
This should be fixed now btw guys

**Comment by joan-aluja** [comment] 2021-10-30 21:34
Thanks! That's great

**Comment by joan-aluja** [comment] 2021-10-31 10:13
I should probably open a new issue but it is still related to this one.
I've used Ann1kaB's void package and the version issue is resolved but I can't install the kernel. It compiles fine but when installing it gives the following error:

> cp: cannot stat 'include/config/dvb/*.h': No such file or directory
=> ERROR: linux514-tkg-pds-5.14.15_21: do_install: 'cp include/config/dvb/*.h ${hdrdest}/include/config/dvb/' exited with 1
=> ERROR:   in do_install() at srcpkgs/linux514-tkg-pds/template:378

Maybe I'm missing something on my part?

I've tried a couple of times but it still gives the same error

**Comment by Ann1kaB** [comment] 2021-11-01 00:45
> I should probably open a new issue but it is still related to this one. I've used Ann1kaB's void package and the version issue is resolved but I can't install the kernel. It compiles fine but when installing it gives the following error:
> 
> > cp: cannot stat 'include/config/dvb/_.h': No such file or directory
> > => ERROR: linux514-tkg-pds-5.14.15_21: do_install: 'cp include/config/dvb/_.h ${hdrdest}/include/config/dvb/' exited with 1
> > => ERROR:   in do_install() at srcpkgs/linux514-tkg-pds/template:378
> 
> Maybe I'm missing something on my part?
> 
> I've tried a couple of times but it still gives the same error

ok this should be fixed too I hope.

**Comment by joan-aluja** [comment] 2021-11-01 18:17
It compiles and installs fine but I'm using BTRFS on my root partition and dracut gives an error when booting, maybe it's because it's compiled as a module?

How do I change the config? I've tried with make menuconfig but it doesn't work inside xbps-src. And the sources get pulled each time i try to compile it.

**Comment by Ann1kaB** [comment] 2021-11-01 18:27
> It compiles and installs fine but I'm using BTRFS on my root partition and dracut gives an error when booting, maybe it's because it's compiled as a module?
> 
> How do I change the config? I've tried with make menuconfig but it doesn't work inside xbps-src. And the sources get pulled each time i try to compile it.

When I had void installed I didn't have a problem with btrfs not booting, do you have rootflags set in grub.cfg? You can change the config when the package first pulls the source, ^C out and go to masterdir/builddir/Linux-tkg/Linux-tkg/config/5.14/config (I think) and change it there if you wish.

Yeah, I could not get menuconfig working in xbps-src and have it actually be usable, rather than not moving the cursor and spitting out key commands instead :/

**Comment by joan-aluja** [comment] 2021-11-01 19:38
> 
> When I had void installed I didn't have a problem with btrfs not booting, do you have rootflags set in grub.cfg? You can change the config when the package first pulls the source, ^C out and go to masterdir/builddir/Linux-tkg/Linux-tkg/config/5.14/config (I think) and change it there if you wish.
> 
> Yeah, I could not get menuconfig working in xbps-src and have it actually be usable, rather than not moving the cursor and spitting out key commands instead :/

I got it working without changing the config. I installed dracut-uefi and added a config in /etc/dracut.conf.d/ with the following
`add_dracutmodules+=" kernel-modules btrfs "`.
And I changed the last column of my /etc/fstab to 0 on my btrfs root partition.

Also we should probably close the issue as it has been fixed.

Thanks Ann1kaB

**Closed** 2021-11-03 06:49 UTC
