### ISSUE TITLE
Fedora 38 - Failing to compile kernel

### ISSUE THREAD

**Issue by ViktorsBaikers** [Frogging-Family/linux-tkg#776] opened 2023-07-25 19:56 UTC
Hi there! So getting such error while trying to compile.

make[3]: *** [scripts/Makefile.vmlinux:36: vmlinux] Error 255
make[3]: *** Deleting file 'vmlinux'
make[2]: *** [Makefile:1253: vmlinux] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.mUlhUn (%build)

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.mUlhUn (%build)
make[1]: *** [scripts/Makefile.package:74: rpm-pkg] Error 1
make: *** [Makefile:1662: rpm-pkg] Error 2
 -> exit cleanup done

/var/tmp/rpm-tmp.mUlhUn contains this:

```
#!/bin/sh

  
  RPM_SOURCE_DIR="/home/brooke/linux-tkg//linux-src-git/linux-tkg-rpmbuild/SOURCES"
  RPM_BUILD_DIR="/home/brooke/linux-tkg//linux-src-git/linux-tkg-rpmbuild/BUILD"
  RPM_OPT_FLAGS="-O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security  -Wp,-D_GLIBCXX_ASSERTIONS    -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  "
  RPM_LD_FLAGS="-Wl,-z,relro -Wl,--as-needed     -Wl,--build-id=none  "
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  RPM_BUILD_NCPUS="32"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_ARCH RPM_OS RPM_BUILD_NCPUS RPM_LD_FLAGS
  RPM_DOC_DIR="/usr/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="kernel"
  RPM_PACKAGE_VERSION="6.4.6_tkg_cfs_g79562f63d621"
  RPM_PACKAGE_RELEASE="1"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  unset DEBUGINFOD_URLS ||:
  RPM_BUILD_ROOT="/home/brooke/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILDROOT/kernel-6.4.6_tkg_cfs_g79562f63d621-1.x86_64"
  export RPM_BUILD_ROOT
  
  PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
  export PKG_CONFIG_PATH
  CONFIG_SITE=${CONFIG_SITE:-NONE}
  export CONFIG_SITE 
  set -x
  umask 022
  cd "/home/brooke/linux-tkg//linux-src-git/linux-tkg-rpmbuild/BUILD" 
   
  
cd 'linux'
make  KERNELRELEASE=6.4.6_tkg_cfs-g79562f63d621 KBUILD_BUILD_VERSION=1



  RPM_EC=$?
  for pid in $(jobs -p); do kill -9 ${pid} || continue; done
  exit ${RPM_EC}
```

Much appreciate your suggestions/help why it may happen.

**Comment by Tk-Glitch** [comment] 2023-07-27 14:29
RPM building breaking every major release is mildly annoying :frog:
Not sure what additional quirk it needs but maybe @AdelKS knows. I'll check that out as soon as I can.

**Comment by AdelKS** [comment] 2023-07-28 19:08
Yeah I wanted to check these issues for so long. Hopefully I'll take the time to do it this weekend

**Comment by AdelKS** [comment] 2023-07-30 19:03
I cannot reproduce this on a docker image of fedora 38, can you attach the files that are asked for in the issue templates, namely the files in the `logs` folder right after a failed install.

**Comment by AdelKS** [comment] 2023-08-15 14:20
I have pushed some fixes today, you should probably be good to go ! Will close this issue, don't hesitate to reopen it.

**Closed by AdelKS** 2023-08-15 14:20 UTC
Labels: bug
